name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for development
      run: npm run build
      env:
        # Development environment variables
        VITE_API_BASE_URL: ${{ secrets.DEV_API_BASE_URL }}
        VITE_AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
        VITE_AWS_USER_POOL_ID: ${{ secrets.DEV_AWS_USER_POOL_ID }}
        VITE_AWS_USER_POOL_WEB_CLIENT_ID: ${{ secrets.DEV_AWS_USER_POOL_WEB_CLIENT_ID }}
        VITE_AWS_IDENTITY_POOL_ID: ${{ secrets.DEV_AWS_IDENTITY_POOL_ID }}
        VITE_AWS_COGNITO_DOMAIN: ${{ secrets.DEV_AWS_COGNITO_DOMAIN }}
        VITE_APP_URL: https://dev.hogodog.jp
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        
    - name: Deploy to S3 (Development)
      run: |
        aws s3 sync ./dist s3://${{ secrets.DEV_S3_BUCKET_NAME }} --delete --exact-timestamps
        
    - name: Invalidate CloudFront (Development)
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
        
    - name: Deployment notification
      run: |
        echo "🚀 Development deployment completed!"
        echo "Website: https://dev.hogodog.jp"